name: Build and push to dockerhub
on:
  push:
    tags:
      - '*'

permissions:
  contents: write

jobs:
  build-and-push:
    name: Build web
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Get robots
      run: |
        wget $(curl -s https://api.github.com/repos/schizo99/robots/releases/latest  | \
          jq -r '.assets[] | select(.name | contains ("robots")) | .browser_download_url')
        tar -xvf robots_x86_64-linux.tar.gz robots

    - name: Get hypertyper
      run: |
        wget $(curl -s https://api.github.com/repos/schizo99/hypertyper/releases/latest  | \
          jq -r '.assets[] | select(.name | contains ("hypertyper")) | .browser_download_url')
        tar -xvf hypertyper_x86_64-linux.tar.gz hypertyper

    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: schizo99/nethack

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ${{ steps.meta.outputs.tags }}

    - name: Create release
      id: create_release
      uses: softprops/action-gh-release@v2
      with:
        generate_release_notes: true
