name: "Test Suite"
on:
  pull_request:

jobs:
  build_test:
    name: test build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get robots
        run: |
          wget $(curl -s https://api.github.com/repos/schizo99/robots/releases/latest  | \
            jq -r '.assets[] | select(.name | contains ("robots")) | .browser_download_url')
          tar -xvf robots_x86_64-linux.tar.gz robots

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: schizo99/nethack

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: false
          tags: ${{ steps.meta.outputs.tags }}