name: "Test Suite"
on:
  pull_request:

jobs:
  build_test:
    name: test build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get robots
        run: |
          wget https://github.com/schizo99/robots/releases/download/v0.1.0/robots_x86_64-linux.tar.gz
          tar -xvf robots_x86_64-linux.tar.gz robots

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: schizo99/nethack

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: false
          tags: ${{ steps.meta.outputs.tags }}